# Generated by Django 4.1.3 on 2023-05-12 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swift', '0002_course_curriculam_emailtemplate_subject_topic_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Curriculam',
            new_name='Curriculum',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='curriculam',
            new_name='curriculum',
        ),
    ]
